-- HMS-BRD-REC-005 §6.5 Premature Form (per-admission neonatal data) + P7b tour vitals log.

CREATE TABLE prem_form (
    id                      UUID PRIMARY KEY,
    admission_id            UUID         NOT NULL,
    visit_id                UUID         NOT NULL,
    patient_id              UUID         NOT NULL,
    age_text                VARCHAR(60),
    birth_weight_kg         NUMERIC(5,3),
    birth_weight_date       DATE,
    current_weight_kg       NUMERIC(5,3),
    current_weight_date     DATE,
    gestational_age_weeks   INTEGER,
    gestational_age_days    INTEGER,
    corrected_ga_weeks      INTEGER,
    corrected_ga_days       INTEGER,
    length_cm               NUMERIC(5,2),
    length_date             DATE,
    ofc_cm                  NUMERIC(5,2),
    ofc_date                DATE,
    feeding_type            VARCHAR(120),
    kcal_per_oz             NUMERIC(7,2),
    enteral_per_kg          NUMERIC(7,2),
    kcal_per_kg             NUMERIC(7,2),
    gir                     NUMERIC(7,2),
    pharmacy_others         VARCHAR(2000),
    last_culture_date       DATE,
    sample_type             VARCHAR(120),
    culture_result          VARCHAR(500),
    prescription_notes      VARCHAR(2000),
    specialist_doctor_notes VARCHAR(2000),
    pharmacy_sign_key       VARCHAR(500),
    pharmacy_sign_name      VARCHAR(200),
    pharmacy_signed_by      UUID,
    pharmacy_signed_at      TIMESTAMPTZ,
    resident_sign_key       VARCHAR(500),
    resident_sign_name      VARCHAR(200),
    resident_signed_by      UUID,
    resident_signed_at      TIMESTAMPTZ,
    senior_sign_key         VARCHAR(500),
    senior_sign_name        VARCHAR(200),
    senior_signed_by        UUID,
    senior_signed_at        TIMESTAMPTZ,
    version                 BIGINT       NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ  NOT NULL,
    created_by              VARCHAR(100),
    updated_at              TIMESTAMPTZ,
    updated_by              VARCHAR(100),
    CONSTRAINT uk_prem_form_admission UNIQUE (admission_id),
    CONSTRAINT fk_prem_form_admission FOREIGN KEY (admission_id) REFERENCES prem_admission(id)
);

CREATE TABLE prem_tour (
    id              UUID PRIMARY KEY,
    admission_id    UUID         NOT NULL,
    tour_type       VARCHAR(10)  NOT NULL,
    recorded_at     TIMESTAMPTZ  NOT NULL,
    recorded_by     UUID,
    resp_rate       INTEGER,
    spo2            INTEGER,
    pulse_rate      INTEGER,
    bowel_motion    VARCHAR(120),
    uop             VARCHAR(120),
    feeding         VARCHAR(200),
    vomiting        VARCHAR(200),
    jaundice        VARCHAR(200),
    iv_access       VARCHAR(200),
    iv_fluid        VARCHAR(200),
    baby_temp_c     NUMERIC(4,1),
    incubator_temp_c NUMERIC(4,1),
    humidity        INTEGER,
    nasal_septum    VARCHAR(200),
    rbs             INTEGER,
    others          VARCHAR(2000),
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),
    CONSTRAINT fk_prem_tour_admission FOREIGN KEY (admission_id) REFERENCES prem_admission(id),
    CONSTRAINT chk_prem_tour_type CHECK (tour_type IN ('MORNING', 'NIGHT'))
);
CREATE INDEX idx_prem_tour_admission ON prem_tour (admission_id, recorded_at DESC);

CREATE TABLE prem_tour_resp_support (
    tour_id      UUID         NOT NULL REFERENCES prem_tour(id) ON DELETE CASCADE,
    resp_support VARCHAR(20)  NOT NULL,
    CONSTRAINT chk_resp_support CHECK (resp_support IN ('MV','CPAP','HFNC','NC','ROOM_AIR')),
    PRIMARY KEY (tour_id, resp_support)
);
